FROM osrf/ros:humble-desktop-full-jammy

ENV DEBIAN_FRONTEND=noninteractive

# Basic ROS 2 setup in .bashrc
RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc

# Install essential tools and ROS 2 navigation/SLAM packages
RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    python3-colcon-common-extensions \
    tmux \
    ruby \
    ruby-dev \
    build-essential \
    wget \
    vim \
    ros-humble-slam-toolbox \
    ros-humble-nav2-bringup \
    ros-humble-nav2-map-server \
    ros-humble-nav2-lifecycle-manager \
    ros-humble-nav2-controller \
    ros-humble-nav2-planner \
    ros-humble-nav2-behavior-tree \
    ros-humble-nav2-costmap-2d \
    ros-humble-nav2-msgs \
    ros-humble-nav2-util \
    ros-humble-nav2-rviz-plugins \
    ros-humble-joint-state-publisher-gui \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-gz-ros2-control \
    ros-humble-gz-ros2-control-demos \
    ros-humble-ros-gz \
    ros-humble-robot-localization \
    ros-humble-ros-gz-bridge \
    ros-humble-ign-ros2-control \
    && rm -rf /var/lib/apt/lists/*

# Install tmuxinator gem
RUN gem install tmuxinator

# Install Libraries
# RUN pip3 install ultralytics face_recognition

# Create ROS 2 workspace and clone robobase package
RUN mkdir -p /root/robows/src && \
    cd /root/robows/src && \
    #    git clone https://github.com/sim-daas/robobase && \
    cd /root/robows && \
    colcon build --symlink-install && \
    echo "source /root/robows/install/setup.bash" >> /root/.bashrc

# Set working directory
WORKDIR /root/
