# my_controllers.yaml

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["lbwheel_joint"]
    right_wheel_names: ["rbwheel_joint"]

    wheel_separation: 0.75
    wheels_per_side: 1
    wheel_radius: 0.2

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10


joint_state_broadcaster:
  ros__parameters:
    joints:
      - lbwheel_joint
      - rbwheel_joint