# my_controllers.yaml

controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["lbwheel_joint"]
    right_wheel_names: ["rbwheel_joint"]

    wheel_separation: 0.75
    wheels_per_side: 1
    wheel_radius: 0.2

    publish_rate: 50.0
    odom_frame_id: odom
    odom_topic: /odom
    base_frame_id: base_footprint
    cmd_vel_timeout: 0.05
    #publish_limited_velocity: true
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    # linear.x.has_velocity_limits: true
    # linear.x.has_acceleration_limits: true
    # linear.x.max_velocity: 1.0
    # linear.x.min_velocity: -1.0
    # linear.x.max_acceleration: 1.0
    # linear.x.max_jerk: .NAN
    # linear.x.min_jerk: .NAN

    # angular.z.has_velocity_limits: true
    # angular.z.has_acceleration_limits: true
    # angular.z.max_velocity: 1.0
    # angular.z.min_velocity: -1.0
    # angular.z.max_acceleration: 1.0
    # angular.z.min_acceleration: -1.0
    # angular.z.max_jerk: .NAN
    # angular.z.min_jerk: .NAN

joint_state_broadcaster:
  ros__parameters:
    joints:
      - lbwheel_joint
      - rbwheel_joint
      - rfwheel_joint
      - lfwheel_joint