# my_controllers.yaml

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

# This is a name we choose for our controller instance
diff_drive_controller:
  ros__parameters:
    # This specifies the type of controller we want to use
    type: diff_drive_controller/DiffDriveController

    # These are the names of the joints from our URDF file
    left_wheel_names: ["lbwheel_joint"]
    right_wheel_names: ["rbwheel_joint"]

    # Other parameters for the controller
    wheel_separation: 0.75
    wheel_radius: 0.2
    publish_rate: 100.0