ekf_filter_node:
  ros__parameters:
    # GENERAL PARAMETERS
    frequency: 100.0                  # Update frequency in Hz
    two_d_mode: true                 # Crucial for flat-ground robots
    publish_tf: true                 # We want the EKF to publish the odom->base_footprint transform

    # FRAME PARAMETERS
    map_frame: map                   # The world-fixed frame, published by SLAM
    odom_frame: odom                 # The odometry frame, published by this EKF node
    base_link_frame: base_footprint  # The robot's base frame

    # SENSOR INPUT 1: Wheel Odometry
    odom0: /diff_drive_controller/odom
    odom0_config: [false, false, false, # [X, Y, Z] position - Not used
                   false, false, true,  # [Roll, Pitch, Yaw] orientation - Only use Yaw
                   true,  true,  false, # [Vx, Vy, Vz] velocity - Use linear X and Y
                   false, false, true,  # [Vroll, Vpitch, Vyaw] angular velocity - Use Yaw velocity
                   false, false, false] # [Ax, Ay, Az] acceleration - Not used
    odom0_differential: false

    # SENSOR INPUT 2: IMU
    imu0: /imu
    imu0_config: [false, false, false, # [X, Y, Z] position - Not used
                  true,  true,  true,  # [Roll, Pitch, Yaw] orientation - Use all three
                  false, false, false, # [Vx, Vy, Vz] velocity - Not used
                  true,  true,  true,  # [Vroll, Vpitch, Vyaw] angular velocity - Use all three
                  true,  true,  true]  # [Ax, Ay, Az] acceleration - Use all three
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true