<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mobile_base">

<xacro:include filename="$(find robobase_description)/models/materials.urdf.xacro"/>
<xacro:include filename="$(find robobase_description)/models/inertia_macros.xacro"/>

<link name="base_footprint">
    <origin xyz="-${base_length / 2} 0 0" rpy="0 0 0"/>
</link>



<!-- Base Link -->
<joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="${base_length / 2} 0 0" rpy="0 0 0"/>
</joint>

<link name="base_link">
    <xacro:inertial_box x="${base_length}" y="${base_width}" z="${base_height}">
        <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
    </xacro:inertial_box>
    <visual>
        <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="gray">
            <xacro:gray/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
    </collision>
</link>



<!-- Lfwheel Link -->
<joint name="lfwheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="lfwheel_link"/>
    <origin xyz="${base_length / 2} ${base_width / 2} 0" rpy="0 0 0"/>
</joint>

<link name="lfwheel_link">
    <xacro:inertial_sphere radius="${castor_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_sphere>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <sphere radius="${castor_radius}"/>
        </geometry>
        <material name="black">
            <xacro:black/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <sphere radius="${castor_radius}"/>
        </geometry>
    </collision>
</link>
<gazebo reference="lfwheel_link">
  <mu1>3.0</mu1>
  <mu2>3.0</mu2>
  <material>Gazebo/Black</material>
</gazebo>



<!-- Rfwheel Link -->
<joint name="rfwheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rfwheel_link"/>
    <origin xyz="${base_length / 2} -${base_width / 2} 0" rpy="0 0 0"/>
</joint>

<link name="rfwheel_link">
    <xacro:inertial_sphere radius="${castor_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_sphere>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <sphere radius="${castor_radius}"/>
        </geometry>
        <material name="black">
            <xacro:black/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <sphere radius="${castor_radius}"/>
        </geometry>
    </collision>
</link>
<gazebo reference="rfwheel_link">
  <mu1>3.0</mu1>
  <mu2>3.0</mu2>
  <material>Gazebo/Black</material>
</gazebo>



<!-- Lbwheel Link -->
<joint name="lbwheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="lbwheel_link"/>
    <origin xyz="-${base_length / 2} ${base_width / 2} ${base_height / 2}" rpy="-${pi / 2} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="lbwheel_link">
    <xacro:inertial_cylinder radius="${wheel_radius}" length="${wheel_width}">
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
    <visual>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
            <xacro:black/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
    </collision>
</link>
<gazebo reference="lbwheel_link">
  <mu1>3.0</mu1>
  <mu2>3.0</mu2>
  <material>Gazebo/Black</material>
</gazebo>



<!-- Rbwheel Link -->
<joint name="rbwheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rbwheel_link"/>
    <origin xyz="-${base_length / 2} -${base_width / 2} ${base_height / 2}" rpy="${pi / 2} 0 0"/>
    <axis xyz="0 0 -1"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="rbwheel_link">
    <xacro:inertial_cylinder radius="${wheel_radius}" length="${wheel_width}">
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
    <visual>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
            <xacro:black/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
    </collision>
</link>
<gazebo reference="rbwheel_link">
  <mu1>3.0</mu1>
  <mu2>3.0</mu2>
  <material>Gazebo/Black</material>
</gazebo>


<gazebo>
  <plugin filename="libgz_ros2_control-system.so" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
    <parameters>/root/robows/src/robobase/mobilerobo/config/controllers.yaml</parameters>
  </plugin>
</gazebo>

<ros2_control name="GazeboSystem" type="system">
    <hardware>
        <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>
    <joint name="lfwheel_joint">
        <state_interface name="position"/>
        <state_interface name="velocity"/>
    </joint>
    <joint name="rfwheel_joint">
        <state_interface name="position"/>
        <state_interface name="velocity"/>
    </joint>
    <joint name="lbwheel_joint">
        <command_interface name="velocity">
        <param name="min">-100</param>
        <param name="max">100</param>
        </command_interface>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
    </joint>
    <joint name="rbwheel_joint">
        <command_interface name="velocity">
        <param name="min">-100</param>
        <param name="max">100</param>
        </command_interface>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
    </joint>
</ros2_control>

</robot>