<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mobile_base">

<xacro:include filename="$(find robobase_description)/models/materials.urdf.xacro"/>
<xacro:include filename="$(find robobase_description)/models/inertia_macros.xacro"/>

<link name="base_footprint">
    <origin xyz="0 0 0" rpy="0 0 0"/>
</link>



<!-- Base Link -->
<joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

<link name="base_link">
    <xacro:inertial_box x="${base_length}" y="${base_width}" z="${base_height}">
        <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
    </xacro:inertial_box>
    <visual>
        <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="gray">
            <xacro:gray/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
    </collision>
</link>



<!-- Lfwheel Link -->
<joint name="lfwheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="lfwheel_link"/>
    <origin xyz="${base_length / 2} ${base_width / 2} ${base_height / 2}" rpy="-${pi / 2} 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<link name="lfwheel_link">
    <xacro:inertial_cylinder radius="${wheel_radius}" length="${wheel_width}">
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
    <visual>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
            <xacro:black/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
    </collision>
</link>
<gazebo reference="lfwheel_link">
  <material>Gazebo/Black</material>
  <kp>1e15</kp>
  <kd>1e14</kd>
  <fdir1>0 0 1</fdir1>
  <mu>1</mu>
  <mu2>1</mu2>
</gazebo>



<!-- Rfwheel Link -->
<joint name="rfwheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rfwheel_link"/>
    <origin xyz="${base_length / 2} -${base_width / 2} ${base_height / 2}" rpy="${pi / 2} 0 0"/>
    <axis xyz="0 0 -1"/>
</joint>

<link name="rfwheel_link">
    <xacro:inertial_cylinder radius="${wheel_radius}" length="${wheel_width}">
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
    <visual>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
            <xacro:black/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
    </collision>
</link>
<gazebo reference="rfwheel_link">
  <material>Gazebo/Black</material>
  <kp>1e15</kp>
  <kd>1e14</kd>
  <fdir1>0 0 1</fdir1>
  <mu>1</mu>
  <mu2>1</mu2>
</gazebo>



<!-- Lbwheel Link -->
<joint name="lbwheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="lbwheel_link"/>
    <origin xyz="-${base_length / 2} ${base_width / 2} ${base_height / 2}" rpy="-${pi / 2} 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<link name="lbwheel_link">
    <xacro:inertial_cylinder radius="${wheel_radius}" length="${wheel_width}">
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
    <visual>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
            <xacro:black/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
    </collision>
</link>
<gazebo reference="lbwheel_link">
  <material>Gazebo/Black</material>
  <kp>1e15</kp>
  <kd>1e14</kd>
  <fdir1>0 0 1</fdir1>
  <mu>1</mu>
  <mu2>1</mu2>
</gazebo>



<!-- Rbwheel Link -->
<joint name="rbwheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rbwheel_link"/>
    <origin xyz="-${base_length / 2} -${base_width / 2} ${base_height / 2}" rpy="${pi / 2} 0 0"/>
    <axis xyz="0 0 -1"/>
</joint>

<link name="rbwheel_link">
    <xacro:inertial_cylinder radius="${wheel_radius}" length="${wheel_width}">
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
    <visual>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
            <xacro:black/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
    </collision>
</link>
<gazebo reference="rbwheel_link">
  <material>Gazebo/Black</material>
  <kp>1e15</kp>
  <kd>1e14</kd>
  <fdir1>0 0 1</fdir1>
  <mu>1</mu>
  <mu2>1</mu2>
</gazebo>

<gazebo>
    <plugin name="gz::sim::systems::JointStatePublisher"
            filename="gz-sim-joint-state-publisher-system">
      <topic>joint_states</topic>
    </plugin>
</gazebo>

</robot>