<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mobile_base">

<xacro:include filename="$(find robobase_description)/models/materials.urdf.xacro"/>
<xacro:include filename="$(find robobase_description)/models/inertia_macros.xacro"/>
<xacro:property name="base_length" default="1"/>
<xacro:property name="base_width" default="0.6"/>
<xacro:property name="base_height" default="0.2"/>
<xacro:property name="wheel_radius" default="0.2"/>
<xacro:property name="wheel_width" default="0.1"/>

<link name="base_footprint">
    <origin xyz="0 0 0" rpy="0 0 0"/>
</link>

<!-- Base Link -->
<joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

<!-- Compute base mass -->
<link name="base_link">
    <xacro:inertial_box x="${base_length}" y="${base_width}" z="${base_height}"/>
    <visual>
        <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="gray">
            <xacro:gray/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
    </collision>
</link>

<!-- Lfwheel Link -->
<joint name="lfwheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="lfwheel_link"/>
    <origin xyz="${base_length / 2} ${base_width / 2} ${base_height / 2}" rpy="-${pi / 2} 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<!-- Compute wheel mass -->
<link name="lfwheel_link">
    <xacro:inertial_cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    <visual>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
            <xacro:black/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
    </collision>
</link>











</robot>