<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Default density in kg/m^3 (e.g., aluminum ~2700) -->
  <xacro:property name="default_density" value="2700"/>

  <xacro:macro name="cylinder_inertia" params="radius length mass:=None density:=${default_density} prefix:=cyl">
    <!-- Calculate mass if not provided -->
    <xacro:if value="${mass == 'None'}">
      <xacro:property name="${prefix}_mass" value="${density * 3.14159265359 * radius * radius * length}"/>
    </xacro:if>
    <xacro:if value="${mass != 'None'}">
      <xacro:property name="${prefix}_mass" value="${mass}"/>
    </xacro:if>
    <!-- Inertia about center (z axis is cylinder axis) -->
    <xacro:property name="${prefix}_ixx" value="${0.5 * ${prefix}_mass * radius * radius}"/>
    <xacro:property name="${prefix}_iyy" value="${0.5 * ${prefix}_mass * radius * radius}"/>
    <xacro:property name="${prefix}_izz" value="${(1/12.0) * ${prefix}_mass * (3 * radius * radius + length * length)}"/>
  </xacro:macro>

  <xacro:macro name="cuboid_inertia" params="x y z mass:=None density:=${default_density} prefix:=cub">
    <!-- Calculate mass if not provided -->
    <xacro:if value="${mass == 'None'}">
      <xacro:property name="${prefix}_mass" value="${density * x * y * z}"/>
    </xacro:if>
    <xacro:if value="${mass != 'None'}">
      <xacro:property name="${prefix}_mass" value="${mass}"/>
    </xacro:if>
    <!-- Inertia about center -->
    <xacro:property name="${prefix}_ixx" value="${(1/12.0) * ${prefix}_mass * (y*y + z*z)}"/>
    <xacro:property name="${prefix}_iyy" value="${(1/12.0) * ${prefix}_mass * (x*x + z*z)}"/>
    <xacro:property name="${prefix}_izz" value="${(1/12.0) * ${prefix}_mass * (x*x + y*y)}"/>
  </xacro:macro>

</robot>
