<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robobase">

<xacro:property name="base_length" default="1"/>
<xacro:property name="base_width" default="0.55"/>
<xacro:property name="base_height" default="0.2"/>
<xacro:property name="wheel_radius" default="0.2"/>
<xacro:property name="castor_radius" default="${wheel_radius / 2}"/>
<xacro:property name="wheel_width" default="0.2"/>
<xacro:property name="camera_xyz" default="0.525 0 0.175"/>
<xacro:property name="camera_rpy" default="0 0 0"/>
<xacro:property name="camera_parent_link" default="base_link"/>
<xacro:property name="lidar_parent_link" default="base_link"/>
<xacro:property name="lidar_xyz" default="0 0 ${base_height + 0.01 + wheel_radius / 2}"/>
<xacro:property name="lidar_rpy" default="0 0 0"/>
<xacro:property name="wheel_separation" default="${base_width + wheel_width}"/>

<xacro:include filename="$(find robobase_description)/models/bases/rectangular-base.urdf.xacro"/>
<xacro:include filename="$(find robobase_description)/models/sensors/camera.urdf.xacro"/>
<xacro:include filename="$(find robobase_description)/models/sensors/lidar.urdf.xacro"/>
<xacro:include filename="$(find robobase_description)/models/sensors/imu.urdf.xacro"/>

</robot>





